### ISSUE TITLE
大哥多账号&隔开无效呢

### ISSUE THREAD

**Issue by zhang-001** [Aellyt/chaoranhui#1]
两个号&隔开只显示一个号

![image](https://github.com/Aellyt/chaoranhui/assets/48820292/bacc34bb-9caa-4518-b8e6-3bd2c6e0aedb)

![image](https://github.com/Aellyt/chaoranhui/assets/48820292/8618f1b8-9b3d-45ed-924b-3d2894a74d9f)

**Comment by zhang-001** [comment]
只填一个号直接这样了哦
![image](https://github.com/Aellyt/chaoranhui/assets/48820292/47ae7857-8bf0-474d-bdc8-2e5642392e64)

**Comment by Aellyt** [comment]
我测试的时候忘记删掉原本单个的变量，导致一直多一个，我还以为我写错了，所以多加了个-1，导致会少一个，稍后我会更新。

**Comment by zhang-001** [comment]
> 我测试的时候忘记删掉原本单个的变量，导致一直多一个，我还以为我写错了，所以多加了个-1，导致会少一个，稍后我会更新。

666
