### ISSUE TITLE
大佬，现在更新啦，一天5次了，还有我的这个错误是什么原因导致的

### ISSUE THREAD

**Issue by SuperNaiBA** [Aellyt/chaoranhui#1]
![image](https://github.com/Aellyt/chaoranhui/assets/33442285/62b75ec9-1eb9-4d88-836a-8756c0089682)

**Comment by Aellyt** [comment]
现在有校验了，所以会报错，电脑端的小程序不知道为何一直无法正常使用，暂时没办法解决，只能手动了

**Comment by Aellyt** [comment]
已更新，可以用了
