### ISSUE TITLE
大佬，中国联通客服公众号里的每日幸运签可以搞一下吗？

### ISSUE THREAD

**Issue by lffw001** [Aellyt/chaoranhui#3]
![QQ截图20240306082837](https://github.com/Aellyt/chaoranhui/assets/27716986/4acde69b-92fb-43ce-b366-f2813b7f1af7)

**Comment by Aellyt** [comment]
大致看了下，这玩意的参数生成得去研究，而且我不觉得这玩意容易给，真要弄有点对不起去研究用的时间

**Comment by lffw001** [comment]
感谢回复
