### ISSUE TITLE
这两天好像不会抽奖了哦

### ISSUE THREAD

**Issue by zhang-001** [Aellyt/chaoranhui#3]

**Comment by zhang-001** [comment]
只有签到了

**Comment by Aellyt** [comment]
他们又提前把新的放出来了，脚本因为上次一次旧的没删会优先用新的，导致没有抽奖，等我后天回家更新下。等明天就会抽了，今天在自己手动下

**Comment by zhang-001** [comment]
> 他们又提前把新的放出来了，脚本因为上次一次旧的没删会优先用新的，导致没有抽奖，等我后天回家更新下。等明天就会抽了，今天在自己手动下

收到

**Comment by zhang-001** [comment]
大佬是不是改一下库存监控脚本或者加个变量控制、有库存通知后继续运行、有时候会再次补库存

**Comment by Aellyt** [comment]
> 大佬是不是改一下库存监控脚本或者加个变量控制、有库存通知后继续运行、有时候会再次补库存
好的，等明天我休息吧

**Comment by zhang-001** [comment]
> > 大佬是不是改一下库存监控脚本或者加个变量控制、有库存通知后继续运行、有时候会再次补库存
> > 好的，等明天我休息吧

666、大佬有tg群不、或者个人tg号、方便 哈哈

**Comment by Aellyt** [comment]
> > > 大佬是不是改一下库存监控脚本或者加个变量控制、有库存通知后继续运行、有时候会再次补库存
> > > 好的，等明天我休息吧
> 
> 666、大佬有tg群不、或者个人tg号、方便 哈哈

有问题这边提吧，我 tg 可能一天看一下，这个还有邮箱提醒我还会看到。

**Comment by zhang-001** [comment]
![image](https://github.com/Aellyt/chaoranhui/assets/48820292/e336e9e0-1bfd-41e4-8148-5b03162b7ce3)
这是什么样情况？
