### ISSUE TITLE
运行ltyd.py报错

### ISSUE THREAD

**Issue by Saxon-Sun** [Aellyt/chaoranhui#5]
Traceback (most recent call last):
  File "/ql/data/scripts/Aellyt_chaoranhui/ltyd.py", line 5, in <module>
    _ = lambda __ : __import__('zlib').decompress(__[::-1]);exec((_)(b'\x9d\x^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 1, in <module>
  File "<string>", line 10, in <module>
ModuleNotFoundError: No module named 'tools.encrypt_symmetric'

## 执行结束... 2024-03-31 11:11:30  耗时 2 秒

已经安装tools pytz pycryptodome依赖

**Comment by Aellyt** [comment]
请完整拉库

**Comment by Saxon-Sun** [comment]
> 请完整拉库

拉的是完整的库 很懵逼  

青龙版本 v2.17.3

![43](https://github.com/Aellyt/chaoranhui/assets/18494610/e47c8742-13ff-46d5-85a0-4c25d1ea4a60)

**Comment by Aellyt** [comment]
我这边没有遇到这样的问题

**Comment by Aellyt** [comment]
https://github.com/limoruirui/misaka可以尝试拉下大佬的库，然后把联通本替换进去试试，还是不行就青龙版本问题，建议使用旧版本，没必要当勇士

**Comment by Saxon-Sun** [comment]
> [https://github.com/limoruirui/misaka可以尝试拉下大佬的库，然后把联通本替换进去试试，还是不行就青龙版本问题，建议使用旧版本，没必要当勇士](https://github.com/limoruirui/misaka%E5%8F%AF%E4%BB%A5%E5%B0%9D%E8%AF%95%E6%8B%89%E4%B8%8B%E5%A4%A7%E4%BD%AC%E7%9A%84%E5%BA%93%EF%BC%8C%E7%84%B6%E5%90%8E%E6%8A%8A%E8%81%94%E9%80%9A%E6%9C%AC%E6%9B%BF%E6%8D%A2%E8%BF%9B%E5%8E%BB%E8%AF%95%E8%AF%95%EF%BC%8C%E8%BF%98%E6%98%AF%E4%B8%8D%E8%A1%8C%E5%B0%B1%E9%9D%92%E9%BE%99%E7%89%88%E6%9C%AC%E9%97%AE%E9%A2%98%EF%BC%8C%E5%BB%BA%E8%AE%AE%E4%BD%BF%E7%94%A8%E6%97%A7%E7%89%88%E6%9C%AC%EF%BC%8C%E6%B2%A1%E5%BF%85%E8%A6%81%E5%BD%93%E5%8B%87%E5%A3%AB)

谢谢大佬 我觉得应该就是青龙版本太高了原因

**Comment by anleihn** [comment]
删除tools依赖就行了

**Comment by Saxon-Sun** [comment]
> 删除tools依赖就行了

真的是删除了tools依赖就可以居然! 谢谢大佬
