### ISSUE TITLE
我想问一下超燃汇库存监控如何进行消息推送？

### ISSUE THREAD

**Issue by Biange00112** [Aellyt/chaoranhui#7]
超燃汇库存监控如何进行消息推送？
推送的话可以有库存的时候进行推送，无库存的时候不进行推送吗？

**Comment by Biange00112** [comment]
目前想用WxPusher进行推送配置，但苦于不会怎么进行推送以及推送的时候只进行有库存消息推送。
大佬看到的话，还请教一下麻烦了。

**Comment by Aellyt** [comment]
是的，脚本是只进行有库存推送的，无库存应该没必要吧，太烦了，过个几分钟就推送一次

**Comment by Biange00112** [comment]
就是我只需要在通知填写WxPusher的相关信息，其他不用动，脚本运行有库存的时候会推送给我，还是我需要做一些其他的相关操作脚本才能推送给我相关的消息？小白不是那么懂，还请多多见谅。

**Comment by Aellyt** [comment]
只需要在青龙面板的通知设置里正确配置即可
