### ISSUE TITLE
阅读更新后出现用户登录已过期

### ISSUE THREAD

**Issue by Soarfree** [Aellyt/chaoranhui#8]
{'code': '9999', 'message': '用户登录已过期', 'innercode': '7777'}

**Comment by Aellyt** [comment]
这个问题已知，偶发性的我暂时没办法解决，目前知道的是leaf的本后跑就会顶掉这边的登录，会出来这个提示。建议把leaf的本设置为2分开始跑

**Comment by anleihn** [comment]
老哥 这个抢阅读任务的sign 加密参数是那些？

**Comment by Aellyt** [comment]
这个你自己f12看下就知道了

**Comment by Aellyt** [comment]
拉下最新的即可，应该是修复了，我测试几天都没问题
